-- MySQL Script generated by MySQL Workbench
-- Sun Feb  2 16:28:44 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema basica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema basica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `basica` DEFAULT CHARACTER SET utf8 ;
USE `basica` ;

-- -----------------------------------------------------
-- Table `basica`.`pages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`pages` (
  `idPages` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `texte` TEXT NULL,
  `tri` INT(11) NOT NULL,
  `created_at` VARCHAR(45) NULL,
  `updated_at` VARCHAR(45) NULL,
  `textlead` TEXT NULL,
  `sous_titre` VARCHAR(75) NULL,
  `onglet` VARCHAR(45) NULL,
  PRIMARY KEY (`idPages`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`posts`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`posts` (
  `idPosts` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL,
  `image` VARCHAR(45) NULL,
  `texteLead` TEXT NULL,
  `texteSuite` TEXT NULL,
  PRIMARY KEY (`idPosts`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`categories` (
  `idcategories` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`posts_has_categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`posts_has_categories` (
  `posts_idPosts` INT UNSIGNED NOT NULL,
  `categories_idcategories` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`posts_idPosts`, `categories_idcategories`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`tags` (
  `idtags` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtags`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`clients` (
  `idclients` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idclients`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`auteurs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`auteurs` (
  `idauteurs` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nom` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idauteurs`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`projets` (
  `idprojets` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `titre` VARCHAR(45) NOT NULL,
  `text` TEXT NULL,
  `image` VARCHAR(45) NULL,
  `clients_idclients` INT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `auteurs_idauteurs` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`idprojets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`tags_has_projets`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`tags_has_projets` (
  `tags_idtags` INT UNSIGNED NOT NULL,
  `projets_idprojets` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`tags_idtags`, `projets_idprojets`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `basica`.`projets_has_tags`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `basica`.`projets_has_tags` (
  `projets_idprojets` INT UNSIGNED NOT NULL,
  `tags_idtags` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`projets_idprojets`, `tags_idtags`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
